from fastapi import APIRouter

from app.api.v1 import (
    ai,
    audit,
    auth,
    boq,
    companies,
    daily_reports,
    documents,
    equipment,
    finance,
    forecast,
    health,
    inventory,
    materials,
    milestones,
    notifications,
    payments,
    procurement,
    project_members,
    projects,
    reports,
    rfqs,
    schedule,
    search,
    suppliers,
    tasks,
    users,
    warehouses,
    workforce,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(companies.router)
api_router.include_router(users.router)
api_router.include_router(reports.router)
api_router.include_router(audit.router)
api_router.include_router(rfqs.router)
api_router.include_router(payments.router)
api_router.include_router(projects.router)
api_router.include_router(project_members.router)
api_router.include_router(milestones.router)
api_router.include_router(tasks.router)
api_router.include_router(tasks.company_router)
api_router.include_router(boq.router)
api_router.include_router(materials.router)
api_router.include_router(warehouses.router)
api_router.include_router(inventory.router)
api_router.include_router(forecast.router)
api_router.include_router(suppliers.router)
api_router.include_router(procurement.router)
api_router.include_router(finance.router)
api_router.include_router(workforce.router)
api_router.include_router(equipment.router)
api_router.include_router(daily_reports.router)
api_router.include_router(ai.router)
api_router.include_router(documents.router)
api_router.include_router(schedule.router)
api_router.include_router(notifications.router)
api_router.include_router(search.router)
